"""OpenCV/Ultralytics/ONNX-ready AOI PCB pipeline for steps 0 through 6.1."""

from .imaging.alignment import AnchorMatch, PCBAligner, StrictAlignmentResult
from .imaging.board import PCBLocalizer
from .classification.family import (
    ComponentClassifier,
    MANIFEST_SCHEMA,
    ONNXComponentClassifier,
    create_classifier,
)
from .classification.package import (
    MANIFEST_SCHEMA as PACKAGE_MANIFEST_SCHEMA,
    MANIFEST_TASK as PACKAGE_MANIFEST_TASK,
    PACKAGE_CLASS_NAMES,
    ONNXPackageClassifier,
    PackageClassification,
    PackageClassifier,
    create_package_classifier,
)
from .imaging.calibration import (
    CalibrationRun,
    CameraCalibrationProfile,
    CameraUndistorter,
    UndistortionResult,
    calibrate_from_chessboards,
    save_calibration_profile,
)
from .config import (
    AlignmentConfig,
    BoardConfig,
    CadConfig,
    ClassificationConfig,
    CropConfig,
    CVDetectorConfig,
    FusionConfig,
    LeadDetectionConfig,
    LeadFusionConfig,
    ModelDetectorConfig,
    PACKAGE_CLASSES,
    PadProfile,
    PackageClassificationConfig,
    PipelineConfig,
    PreprocessConfig,
    SolderGradingConfig,
    SolderDefectDetectionConfig,
    SolderJointConfig,
    TilingConfig,
    terminal_geometry,
)
from .detection.cropping import ComponentCropper
from .detection.detectors import (
    CVComponentDetector,
    ComponentDetector,
    MockComponentDetector,
    UltralyticsDetector,
    create_detector,
    non_maximum_suppression,
)
from .reporting.evidence import (
    DefectEvidence,
    EvidenceBundle,
    EvidenceMismatch,
    EvidenceViewer,
    SourceFingerprint,
    build_evidence_bundle,
)
from .exceptions import (
    AlignmentError,
    AOIPipelineError,
    CalibrationProfileError,
    ClassifierConfigurationError,
    DetectorConfigurationError,
    ExportError,
    InvalidImageError,
    ModelDependencyError,
    RecipeValidationError,
)
from .reporting.exporters import (
    cad_findings_csv,
    export_json,
    export_zip,
    package_classifications_csv,
    package_topology_checks_csv,
    solder_joints_csv,
    solder_verdicts_csv,
)
from .placement.footprints import (
    FootprintProfile,
    normalize_footprint,
    parse_footprint,
    profile_for_package_class,
)
from .reporting.overlays import (
    render_annotations,
    render_solder_overlay,
    render_verdict_overlay,
)
from .golden.compare import GoldenComparator, GoldenCompareConfig, GoldenCompareResult
from .imaging.image_io import encode_image, ensure_bgr, letterbox_normalize, load_image
from .solder.cad import (
    CAD_LOADERS,
    BoardCad,
    CadComponent,
    CadError,
    CadPad,
    CadRegistration,
    classes_agree,
    designator_to_class,
    is_informative_label,
    load_cad,
    register_cad,
    register_from_fiducials,
    save_cad_json,
)
from .solder.cad_fusion import CadFinding, FusionResult, fuse_solder_joints
from .solder.leads import (
    LEAD_CLASSES,
    LeadFusionResult,
    fuse_detected_leads,
    split_lead_detections,
)
from .solder.geometry import (
    ComponentFrame,
    SolderJointCropper,
    derive_solder_joints,
    estimate_component_angle,
)
from .solder.package_validation import (
    PackageTopologyCheck,
    assess_package_topology,
)
from .solder.defect_detection import (
    SOLDER_DEFECT_CLASS_NAMES,
    SOLDER_DEFECT_MANIFEST_SCHEMA,
    SOLDER_DEFECT_SOURCE,
    SOLDER_DEFECT_TASK,
    SolderDefectContract,
    SolderDefectDetector,
    create_solder_defect_detector,
    validate_solder_defect_manifest,
)
from .grading.classifier import (
    MANIFEST_SCHEMA as SOLDER_MANIFEST_SCHEMA,
    ONNXSolderClassifier,
    create_solder_classifier,
)
from .grading.features import measure_solder, segment_solder
from .grading.inspector import SolderInspector
from .grading.rules import (
    COMPONENT_CLASSES,
    JOINT_CLASSES,
    grade_component_by_rules,
    grade_joint_by_rules,
)
from .golden.inspector import (
    AOIInspector,
    DetectionSummary,
    InspectionConfig,
    InspectionRun,
    SlotInspectionResult,
    render_inspection_overlay,
)
from .models import (
    SolderFeatures,
    SolderJoint,
    SolderJointCrop,
    SolderVerdict,
    AlignmentResult,
    BoardRegion,
    BoundingBox,
    ClassProbability,
    ComponentClassification,
    ComponentCrop,
    Detection,
    PipelineRun,
    PreprocessResult,
)
from .pipeline import AOIPipeline
from .golden.position import PositionMeasurer, PositionQualityGates, PositionResult
from .imaging.preprocessing import ImagePreprocessor
from .golden.recipe import (
    AppearanceThresholds,
    AlignmentAnchor,
    AlignmentQualityGates,
    AlignmentRecipe,
    DEFAULT_BOARD_SIDE,
    DEMO_BOARD_ID,
    GOLDEN_COORDINATE_SPACE,
    ImageSize,
    InspectionRecipe,
    MetrologyCalibration,
    PositionTolerance,
    RECIPE_SCHEMA_VERSION,
    RecipeBuildResult,
    RejectedDetection,
    SlotRecipe,
    create_recipe,
    create_grid_alignment_recipe,
    load_recipe,
    save_recipe,
    validate_recipe_assets,
)
from .detection.tiling import (
    InferenceTile,
    TiledDetectionBatch,
    detect_with_adaptive_tiling,
    merge_tiled_detections,
    plan_inference_tiles,
)

__all__ = [
    "DefectEvidence",
    "EvidenceBundle",
    "EvidenceMismatch",
    "EvidenceViewer",
    "SourceFingerprint",
    "build_evidence_bundle",
    "AOIPipeline",
    "AOIInspector",
    "AOIPipelineError",
    "AlignmentConfig",
    "AlignmentError",
    "AlignmentResult",
    "AnchorMatch",
    "AlignmentAnchor",
    "AlignmentQualityGates",
    "AlignmentRecipe",
    "AppearanceThresholds",
    "DEFAULT_BOARD_SIDE",
    "DEMO_BOARD_ID",
    "BoardConfig",
    "BoardRegion",
    "BoundingBox",
    "CalibrationProfileError",
    "CalibrationRun",
    "ClassProbability",
    "ClassificationConfig",
    "PackageClassificationConfig",
    "ClassifierConfigurationError",
    "CVComponentDetector",
    "CVDetectorConfig",
    "CameraCalibrationProfile",
    "CameraUndistorter",
    "ComponentCrop",
    "ComponentClassification",
    "ComponentClassifier",
    "ComponentCropper",
    "ComponentDetector",
    "CropConfig",
    "Detection",
    "DetectionSummary",
    "DetectorConfigurationError",
    "ExportError",
    "GoldenComparator",
    "GoldenCompareConfig",
    "GoldenCompareResult",
    "ImagePreprocessor",
    "ImageSize",
    "InspectionRecipe",
    "InspectionConfig",
    "InspectionRun",
    "InferenceTile",
    "InvalidImageError",
    "MockComponentDetector",
    "ModelDependencyError",
    "ModelDetectorConfig",
    "MetrologyCalibration",
    "MANIFEST_SCHEMA",
    "PACKAGE_CLASSES",
    "PACKAGE_CLASS_NAMES",
    "PACKAGE_MANIFEST_SCHEMA",
    "PACKAGE_MANIFEST_TASK",
    "PackageClassification",
    "PackageClassifier",
    "PackageTopologyCheck",
    "ONNXPackageClassifier",
    "ONNXComponentClassifier",
    "PCBAligner",
    "PCBLocalizer",
    "PipelineConfig",
    "PipelineRun",
    "PreprocessConfig",
    "PreprocessResult",
    "PositionTolerance",
    "PositionMeasurer",
    "PositionQualityGates",
    "PositionResult",
    "RECIPE_SCHEMA_VERSION",
    "RecipeBuildResult",
    "RecipeValidationError",
    "RejectedDetection",
    "SlotRecipe",
    "StrictAlignmentResult",
    "SlotInspectionResult",
    "render_inspection_overlay",
    "TiledDetectionBatch",
    "TilingConfig",
    "UltralyticsDetector",
    "UndistortionResult",
    "calibrate_from_chessboards",
    "create_detector",
    "create_classifier",
    "create_package_classifier",
    "create_recipe",
    "create_grid_alignment_recipe",
    "detect_with_adaptive_tiling",
    "encode_image",
    "ensure_bgr",
    "export_json",
    "export_zip",
    "package_classifications_csv",
    "package_topology_checks_csv",
    "load_image",
    "load_recipe",
    "merge_tiled_detections",
    "non_maximum_suppression",
    "plan_inference_tiles",
    "render_annotations",
    "save_recipe",
    "save_calibration_profile",
    "validate_recipe_assets",
    "GOLDEN_COORDINATE_SPACE",
    "BoardCad",
    "CAD_LOADERS",
    "COMPONENT_CLASSES",
    "CadComponent",
    "CadConfig",
    "CadError",
    "CadFinding",
    "CadPad",
    "CadRegistration",
    "ComponentFrame",
    "FusionConfig",
    "FusionResult",
    "FootprintProfile",
    "JOINT_CLASSES",
    "LEAD_CLASSES",
    "LeadDetectionConfig",
    "LeadFusionConfig",
    "LeadFusionResult",
    "ONNXSolderClassifier",
    "PadProfile",
    "SOLDER_MANIFEST_SCHEMA",
    "SolderFeatures",
    "SolderDefectContract",
    "SolderDefectDetectionConfig",
    "SolderDefectDetector",
    "SolderGradingConfig",
    "SolderInspector",
    "SolderJoint",
    "SolderJointConfig",
    "SolderJointCrop",
    "SolderJointCropper",
    "SolderVerdict",
    "cad_findings_csv",
    "classes_agree",
    "create_solder_classifier",
    "create_solder_defect_detector",
    "derive_solder_joints",
    "designator_to_class",
    "estimate_component_angle",
    "fuse_detected_leads",
    "fuse_solder_joints",
    "grade_component_by_rules",
    "grade_joint_by_rules",
    "is_informative_label",
    "letterbox_normalize",
    "load_cad",
    "measure_solder",
    "normalize_footprint",
    "parse_footprint",
    "profile_for_package_class",
    "register_cad",
    "register_from_fiducials",
    "render_solder_overlay",
    "render_verdict_overlay",
    "save_cad_json",
    "segment_solder",
    "solder_joints_csv",
    "solder_verdicts_csv",
    "split_lead_detections",
    "terminal_geometry",
    "assess_package_topology",
    "validate_solder_defect_manifest",
    "SOLDER_DEFECT_CLASS_NAMES",
    "SOLDER_DEFECT_MANIFEST_SCHEMA",
    "SOLDER_DEFECT_SOURCE",
    "SOLDER_DEFECT_TASK",
]

__version__ = "0.2.0"
