"""OpenCV/Ultralytics/ONNX-ready AOI PCB pipeline for steps 0 through 6.1."""

from .alignment import AnchorMatch, PCBAligner, StrictAlignmentResult
from .board import PCBLocalizer
from .classification import (
    ComponentClassifier,
    MANIFEST_SCHEMA,
    ONNXComponentClassifier,
    create_classifier,
)
from .calibration import (
    CalibrationRun,
    CameraCalibrationProfile,
    CameraUndistorter,
    UndistortionResult,
    calibrate_from_chessboards,
    save_calibration_profile,
)
from .config import (
    AlignmentConfig,
    BoardConfig,
    ClassificationConfig,
    CropConfig,
    CVDetectorConfig,
    ModelDetectorConfig,
    PipelineConfig,
    PreprocessConfig,
    TilingConfig,
)
from .cropping import ComponentCropper
from .detectors import (
    CVComponentDetector,
    ComponentDetector,
    MockComponentDetector,
    UltralyticsDetector,
    create_detector,
    non_maximum_suppression,
)
from .exceptions import (
    AlignmentError,
    AOIPipelineError,
    CalibrationProfileError,
    ClassifierConfigurationError,
    DetectorConfigurationError,
    ExportError,
    InvalidImageError,
    ModelDependencyError,
    RecipeValidationError,
)
from .exporters import export_json, export_zip, render_annotations
from .golden_compare import GoldenComparator, GoldenCompareConfig, GoldenCompareResult
from .image_io import encode_image, ensure_bgr, load_image
from .inspection import (
    AOIInspector,
    DetectionSummary,
    InspectionConfig,
    InspectionRun,
    SlotInspectionResult,
    render_inspection_overlay,
)
from .models import (
    AlignmentResult,
    BoardRegion,
    BoundingBox,
    ClassProbability,
    ComponentClassification,
    ComponentCrop,
    Detection,
    PipelineRun,
    PreprocessResult,
)
from .pipeline import AOIPipeline
from .position import PositionMeasurer, PositionQualityGates, PositionResult
from .preprocessing import ImagePreprocessor
from .recipe import (
    AppearanceThresholds,
    AlignmentAnchor,
    AlignmentQualityGates,
    AlignmentRecipe,
    DEFAULT_BOARD_SIDE,
    DEMO_BOARD_ID,
    GOLDEN_COORDINATE_SPACE,
    ImageSize,
    InspectionRecipe,
    MetrologyCalibration,
    PositionTolerance,
    RECIPE_SCHEMA_VERSION,
    RecipeBuildResult,
    RejectedDetection,
    SlotRecipe,
    create_recipe,
    create_grid_alignment_recipe,
    load_recipe,
    save_recipe,
    validate_recipe_assets,
)
from .tiling import (
    InferenceTile,
    TiledDetectionBatch,
    detect_with_adaptive_tiling,
    merge_tiled_detections,
    plan_inference_tiles,
)

__all__ = [
    "AOIPipeline",
    "AOIInspector",
    "AOIPipelineError",
    "AlignmentConfig",
    "AlignmentError",
    "AlignmentResult",
    "AnchorMatch",
    "AlignmentAnchor",
    "AlignmentQualityGates",
    "AlignmentRecipe",
    "AppearanceThresholds",
    "DEFAULT_BOARD_SIDE",
    "DEMO_BOARD_ID",
    "BoardConfig",
    "BoardRegion",
    "BoundingBox",
    "CalibrationProfileError",
    "CalibrationRun",
    "ClassProbability",
    "ClassificationConfig",
    "ClassifierConfigurationError",
    "CVComponentDetector",
    "CVDetectorConfig",
    "CameraCalibrationProfile",
    "CameraUndistorter",
    "ComponentCrop",
    "ComponentClassification",
    "ComponentClassifier",
    "ComponentCropper",
    "ComponentDetector",
    "CropConfig",
    "Detection",
    "DetectionSummary",
    "DetectorConfigurationError",
    "ExportError",
    "GoldenComparator",
    "GoldenCompareConfig",
    "GoldenCompareResult",
    "ImagePreprocessor",
    "ImageSize",
    "InspectionRecipe",
    "InspectionConfig",
    "InspectionRun",
    "InferenceTile",
    "InvalidImageError",
    "MockComponentDetector",
    "ModelDependencyError",
    "ModelDetectorConfig",
    "MetrologyCalibration",
    "MANIFEST_SCHEMA",
    "ONNXComponentClassifier",
    "PCBAligner",
    "PCBLocalizer",
    "PipelineConfig",
    "PipelineRun",
    "PreprocessConfig",
    "PreprocessResult",
    "PositionTolerance",
    "PositionMeasurer",
    "PositionQualityGates",
    "PositionResult",
    "RECIPE_SCHEMA_VERSION",
    "RecipeBuildResult",
    "RecipeValidationError",
    "RejectedDetection",
    "SlotRecipe",
    "StrictAlignmentResult",
    "SlotInspectionResult",
    "render_inspection_overlay",
    "TiledDetectionBatch",
    "TilingConfig",
    "UltralyticsDetector",
    "UndistortionResult",
    "calibrate_from_chessboards",
    "create_detector",
    "create_classifier",
    "create_recipe",
    "create_grid_alignment_recipe",
    "detect_with_adaptive_tiling",
    "encode_image",
    "ensure_bgr",
    "export_json",
    "export_zip",
    "load_image",
    "load_recipe",
    "merge_tiled_detections",
    "non_maximum_suppression",
    "plan_inference_tiles",
    "render_annotations",
    "save_recipe",
    "save_calibration_profile",
    "validate_recipe_assets",
    "GOLDEN_COORDINATE_SPACE",
]

__version__ = "0.2.0"
