"""OpenCV/Ultralytics/ONNX-ready AOI PCB pipeline for steps 0 through 6.1."""

from .alignment import PCBAligner
from .board import PCBLocalizer
from .classification import (
    ComponentClassifier,
    MANIFEST_SCHEMA,
    ONNXComponentClassifier,
    create_classifier,
)
from .calibration import (
    CalibrationRun,
    CameraCalibrationProfile,
    CameraUndistorter,
    UndistortionResult,
    calibrate_from_chessboards,
    save_calibration_profile,
)
from .config import (
    AlignmentConfig,
    BoardConfig,
    ClassificationConfig,
    CropConfig,
    CVDetectorConfig,
    ModelDetectorConfig,
    PadProfile,
    PipelineConfig,
    PreprocessConfig,
    SolderJointConfig,
    TilingConfig,
    terminal_geometry,
)
from .cropping import ComponentCropper
from .detectors import (
    CVComponentDetector,
    ComponentDetector,
    MockComponentDetector,
    UltralyticsDetector,
    create_detector,
    non_maximum_suppression,
)
from .exceptions import (
    AlignmentError,
    AOIPipelineError,
    CalibrationProfileError,
    ClassifierConfigurationError,
    DetectorConfigurationError,
    ExportError,
    InvalidImageError,
    ModelDependencyError,
)
from .exporters import export_json, export_zip, render_annotations, solder_joints_csv
from .image_io import encode_image, ensure_bgr, load_image
from .models import (
    AlignmentResult,
    BoardRegion,
    BoundingBox,
    ClassProbability,
    ComponentClassification,
    ComponentCrop,
    Detection,
    PipelineRun,
    PreprocessResult,
    SolderJoint,
    SolderJointCrop,
)
from .pipeline import AOIPipeline
from .preprocessing import ImagePreprocessor
from .solder import (
    SolderJointCropper,
    derive_solder_joints,
    estimate_component_angle,
    letterbox_normalize,
    render_solder_overlay,
)
from .tiling import (
    InferenceTile,
    TiledDetectionBatch,
    detect_with_adaptive_tiling,
    merge_tiled_detections,
    plan_inference_tiles,
)

__all__ = [
    "AOIPipeline",
    "AOIPipelineError",
    "AlignmentConfig",
    "AlignmentError",
    "AlignmentResult",
    "BoardConfig",
    "BoardRegion",
    "BoundingBox",
    "CalibrationProfileError",
    "CalibrationRun",
    "ClassProbability",
    "ClassificationConfig",
    "ClassifierConfigurationError",
    "CVComponentDetector",
    "CVDetectorConfig",
    "CameraCalibrationProfile",
    "CameraUndistorter",
    "ComponentCrop",
    "ComponentClassification",
    "ComponentClassifier",
    "ComponentCropper",
    "ComponentDetector",
    "CropConfig",
    "Detection",
    "DetectorConfigurationError",
    "ExportError",
    "ImagePreprocessor",
    "InferenceTile",
    "InvalidImageError",
    "MockComponentDetector",
    "ModelDependencyError",
    "ModelDetectorConfig",
    "MANIFEST_SCHEMA",
    "ONNXComponentClassifier",
    "PCBAligner",
    "PCBLocalizer",
    "PadProfile",
    "PipelineConfig",
    "PipelineRun",
    "PreprocessConfig",
    "PreprocessResult",
    "SolderJoint",
    "SolderJointConfig",
    "SolderJointCrop",
    "SolderJointCropper",
    "TiledDetectionBatch",
    "TilingConfig",
    "UltralyticsDetector",
    "UndistortionResult",
    "calibrate_from_chessboards",
    "create_detector",
    "create_classifier",
    "derive_solder_joints",
    "detect_with_adaptive_tiling",
    "encode_image",
    "ensure_bgr",
    "estimate_component_angle",
    "export_json",
    "export_zip",
    "letterbox_normalize",
    "load_image",
    "merge_tiled_detections",
    "non_maximum_suppression",
    "plan_inference_tiles",
    "render_annotations",
    "render_solder_overlay",
    "save_calibration_profile",
    "solder_joints_csv",
    "terminal_geometry",
]

__version__ = "0.3.0"
