[theme]
base = "light"
primaryColor = "#38BDF8"
backgroundColor = "#F3F7FB"
secondaryBackgroundColor = "#FFFFFF"
textColor = "#102033"
font = "sans-serif"

[server]
maxUploadSize = 256

[browser]
gatherUsageStats = false
